const express = require('express')
const router = express.Router()
const userController = require('../controllers/userController')
const userMiddleware = require('../helpers/users')
const { sendResponse } = require('../helpers/response')
const { uploadMidleware } = require('../helpers/uploadMidleware')
const SendEmail = require('../helpers/email')

router.route('/').get(userMiddleware.isLoggedIn, userController.getUserById, sendResponse)
router.route('/edit-profile').patch(userMiddleware.isLoggedIn, userController.getUserById, uploadMidleware, userController.editProfile, sendResponse)
router.route('/update-password').post(userMiddleware.isLoggedIn, userController.updatePassword, sendResponse)
router.route('/forgot-password').post(userController.forgetPassword, SendEmail, sendResponse)
router.route('/login').post(userMiddleware.validateLogin, userController.login, sendResponse)
router.route('/logout').get(userMiddleware.isLoggedIn, userController.logout, sendResponse)
router.route('/sign-up').post(userMiddleware.validateSignup, userController.signUp, SendEmail, sendResponse)
router.route('/verifikasi-email/:token').get(userController.verifikasiEmail, sendResponse)
router.route('/customer-address')
  .post(userMiddleware.isLoggedIn, userController.insertAddress, sendResponse)
  .get(userMiddleware.isLoggedIn, userController.getAllCustomerAddress, sendResponse)
//   .delete()
module.exports = router
